import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import InventoryContextProvider from '@/context/InventoryContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Game Inventory',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='w-full min-h-screen py-4 px-8 bg-slate-700 text-gray-100'>
        
        <InventoryContextProvider>
          <header className='w-full flex flex-col justify-center items-center gap-10'>
            <h1 className='text-3xl font-bold'>Game Inventory Mini Project</h1>
            <nav>
              <ul className='flex justify-center items-center gap-4'>
                <li>
                  <Link href={"/"} className='py-2 px-4 bg-slate-500 rounded hover:bg-slate-600'>Inventory</Link>
                </li>
                <li>
                  <Link href={"/character"} className='py-2 px-4 bg-slate-500 rounded hover:bg-slate-600'>Character</Link>
                </li>
              </ul>
            </nav>
          </header>
          <main className='w-full flex flex-col justify-start items-center pt-16 px-12'>
            {children}
          </main>
        </InventoryContextProvider>

      </body>
    </html>
  )
}
